services:
  clipharborbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clipharborbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - clipharbor-temp:/app/temp
  cloudflared:
    image: docker.io/cloudflare/cloudflared:2025.11.1-amd64
    container_name: cloudflared
    restart: unless-stopped

    profiles:
      - tunnel
    command: tunnel run --url http://clipharborbot:2000 --token ${CLOUDFLARE_TUNNEL_TOKEN}

    depends_on:
      - clipharborbot

volumes:
  clipharbor-temp:
